//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorPraktPM11
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_log
    {
        public int id_log { get; set; }
        public Nullable<int> id_employee { get; set; }
        public string action_type { get; set; }
        public string table_name { get; set; }
        public int record_id { get; set; }
        public Nullable<System.DateTime> action_datetime { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public string ip_address { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual users users { get; set; }
    }
}
