//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorPraktPM11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MunicipalRentDBEntities2 : DbContext
    {
        public MunicipalRentDBEntities2()
            : base("name=MunicipalRentDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<audit_log> audit_log { get; set; }
        public DbSet<contracts> contracts { get; set; }
        public DbSet<departments> departments { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<objects> objects { get; set; }
        public DbSet<payments> payments { get; set; }
        public DbSet<positions> positions { get; set; }
        public DbSet<tenants> tenants { get; set; }
        public DbSet<users> users { get; set; }
    }
}
