//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorPraktPM11
{
    using System;
    using System.Collections.Generic;
    
    public partial class objects
    {
        public objects()
        {
            this.contracts = new HashSet<contracts>();
        }
    
        public int id_object { get; set; }
        public string address { get; set; }
        public string cadastral_number { get; set; }
        public string type { get; set; }
        public Nullable<decimal> total_area { get; set; }
        public string purpose { get; set; }
        public string condition { get; set; }
        public Nullable<bool> is_rented_now { get; set; }
    
        public virtual ICollection<contracts> contracts { get; set; }
    }
}
