//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorPraktPM11
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int id_payment { get; set; }
        public int id_contract { get; set; }
        public System.DateTime payment_date { get; set; }
        public System.DateTime period_month { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string payment_type { get; set; }
        public Nullable<bool> is_penalty { get; set; }
        public int id_employee_who_accepted { get; set; }
        public string receipt_number { get; set; }
        public Nullable<int> id_user_who_accepted { get; set; }
    
        public virtual contracts contracts { get; set; }
        public virtual employees employees { get; set; }
    }
}
