//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorPraktPM11
{
    using System;
    using System.Collections.Generic;
    
    public partial class positions
    {
        public positions()
        {
            this.employees = new HashSet<employees>();
        }
    
        public int id_position { get; set; }
        public string position_name { get; set; }
        public string salary_grade { get; set; }
        public Nullable<int> access_level { get; set; }
        public Nullable<decimal> base_salary { get; set; }
    
        public virtual ICollection<employees> employees { get; set; }
    }
}
