//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorPraktPM11
{
    using System;
    using System.Collections.Generic;
    
    public partial class contracts
    {
        public contracts()
        {
            this.payments = new HashSet<payments>();
        }
    
        public int id_contract { get; set; }
        public string contract_number { get; set; }
        public int id_object { get; set; }
        public int id_tenant { get; set; }
        public int id_responsible_employee { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<decimal> monthly_rate { get; set; }
        public Nullable<int> payment_day { get; set; }
        public string contract_status { get; set; }
        public string notes { get; set; }
    
        public virtual objects objects { get; set; }
        public virtual employees employees { get; set; }
        public virtual ICollection<payments> payments { get; set; }
    }
}
