//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorPraktPM11
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public employees()
        {
            this.contracts = new HashSet<contracts>();
            this.payments = new HashSet<payments>();
        }
    
        public int id_employee { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public Nullable<int> id_position { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string role { get; set; }
        public int department { get; set; }
    
        public virtual ICollection<contracts> contracts { get; set; }
        public virtual positions positions { get; set; }
        public virtual ICollection<payments> payments { get; set; }
        public virtual departments departments { get; set; }
    }
}
