//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendatorPraktPM11
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenants
    {
        public int id_tenant { get; set; }
        public string type { get; set; }
        public string inn { get; set; }
        public string ogrn { get; set; }
        public string short_name { get; set; }
        public string full_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string legal_address { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public Nullable<int> id_user { get; set; }
    }
}
